<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" retried="6" total="20" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Open Cart Regression Suite" duration-ms="119754" started-at="2022-05-04T18:11:56 IST" finished-at="2022-05-04T18:13:56 IST">
    <groups>
    </groups>
    <test name="Login Page Test" duration-ms="39330" started-at="2022-05-04T18:11:56 IST" finished-at="2022-05-04T18:12:36 IST">
      <class name="com.ba.democart.tests.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="setup" is-config="true" duration-ms="8184" started-at="2022-05-04T18:11:56 IST" finished-at="2022-05-04T18:12:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginpageTitleTest()[pri:1, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginpageTitleTest" duration-ms="10419" started-at="2022-05-04T18:12:05 IST" finished-at="2022-05-04T18:12:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginpageTitleTest -->
        <test-method status="SKIP" signature="loginPageHeaderTest()[pri:2, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginPageHeaderTest" duration-ms="1765" retried="true" started-at="2022-05-04T18:12:16 IST" finished-at="2022-05-04T18:12:17 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.ba.democart.tests.LoginPageTest.loginPageHeaderTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageHeaderTest -->
        <test-method status="SKIP" signature="loginPageHeaderTest()[pri:2, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginPageHeaderTest" duration-ms="1691" retried="true" started-at="2022-05-04T18:12:18 IST" finished-at="2022-05-04T18:12:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.ba.democart.tests.LoginPageTest.loginPageHeaderTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageHeaderTest -->
        <test-method status="SKIP" signature="loginPageHeaderTest()[pri:2, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginPageHeaderTest" duration-ms="1631" retried="true" started-at="2022-05-04T18:12:20 IST" finished-at="2022-05-04T18:12:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.ba.democart.tests.LoginPageTest.loginPageHeaderTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageHeaderTest -->
        <test-method status="FAIL" signature="loginPageHeaderTest()[pri:2, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginPageHeaderTest" duration-ms="1666" started-at="2022-05-04T18:12:22 IST" finished-at="2022-05-04T18:12:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ..THE HEADER IS NOT MATCHED... expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.ba.democart.tests.LoginPageTest.loginPageHeaderTest(LoginPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageHeaderTest -->
        <test-method status="PASS" signature="forgotPwdLinkText()[pri:3, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="forgotPwdLinkText" duration-ms="1643" started-at="2022-05-04T18:12:24 IST" finished-at="2022-05-04T18:12:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPwdLinkText -->
        <test-method status="PASS" signature="loginTest()[pri:4, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="loginTest" duration-ms="10250" started-at="2022-05-04T18:12:26 IST" finished-at="2022-05-04T18:12:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ba.democart.tests.LoginPageTest@61f39bb]" name="tearDown" is-config="true" duration-ms="0" started-at="2022-05-04T18:12:36 IST" finished-at="2022-05-04T18:12:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ba.democart.tests.LoginPageTest -->
    </test> <!-- Login Page Test -->
    <test name="Accounts Page Test" duration-ms="78506" started-at="2022-05-04T18:12:38 IST" finished-at="2022-05-04T18:13:56 IST">
      <class name="com.ba.democart.tests.AccountsPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="setup" is-config="true" duration-ms="3929" started-at="2022-05-04T18:12:38 IST" finished-at="2022-05-04T18:12:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="accPageSetup()[pri:0, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageSetup" is-config="true" duration-ms="7665" started-at="2022-05-04T18:12:42 IST" finished-at="2022-05-04T18:12:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageSetup -->
        <test-method status="PASS" signature="accPageTitleTest()[pri:1, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageTitleTest" duration-ms="21" started-at="2022-05-04T18:12:49 IST" finished-at="2022-05-04T18:12:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageTitleTest -->
        <test-method status="SKIP" signature="accPageHeaderTest()[pri:2, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageHeaderTest" duration-ms="1665" retried="true" started-at="2022-05-04T18:12:49 IST" finished-at="2022-05-04T18:12:51 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ba.democart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageHeaderTest -->
        <test-method status="SKIP" signature="accPageHeaderTest()[pri:2, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageHeaderTest" duration-ms="1649" retried="true" started-at="2022-05-04T18:12:51 IST" finished-at="2022-05-04T18:12:53 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ba.democart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageHeaderTest -->
        <test-method status="SKIP" signature="accPageHeaderTest()[pri:2, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageHeaderTest" duration-ms="1676" retried="true" started-at="2022-05-04T18:12:53 IST" finished-at="2022-05-04T18:12:55 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ba.democart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageHeaderTest -->
        <test-method status="FAIL" signature="accPageHeaderTest()[pri:2, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accPageHeaderTest" duration-ms="1594" started-at="2022-05-04T18:12:55 IST" finished-at="2022-05-04T18:12:57 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Store11] but found [Your Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ba.democart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accPageHeaderTest -->
        <test-method status="PASS" signature="accSectionListTest()[pri:3, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="accSectionListTest" duration-ms="155" started-at="2022-05-04T18:12:57 IST" finished-at="2022-05-04T18:12:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accSectionListTest -->
        <test-method status="PASS" signature="logoutLinkExistTest()[pri:4, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="logoutLinkExistTest" duration-ms="1769" started-at="2022-05-04T18:12:57 IST" finished-at="2022-05-04T18:12:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutLinkExistTest -->
        <test-method status="PASS" signature="searchTest(java.lang.String)[pri:5, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="searchTest" duration-ms="7571" started-at="2022-05-04T18:12:59 IST" data-provider="getSearchData" finished-at="2022-05-04T18:13:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Macbook Pro]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="searchTest(java.lang.String)[pri:5, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="searchTest" duration-ms="7504" started-at="2022-05-04T18:13:07 IST" data-provider="getSearchData" finished-at="2022-05-04T18:13:14 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Macbook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="searchTest(java.lang.String)[pri:5, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="searchTest" duration-ms="7438" started-at="2022-05-04T18:13:14 IST" data-provider="getSearchData" finished-at="2022-05-04T18:13:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Apple]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchTest -->
        <test-method status="PASS" signature="selectProductTest(java.lang.String,java.lang.String)[pri:6, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="selectProductTest" duration-ms="11411" started-at="2022-05-04T18:13:25 IST" data-provider="getProductSelectData" finished-at="2022-05-04T18:13:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Macbook]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[MacBook Pro]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProductTest -->
        <test-method status="PASS" signature="selectProductTest(java.lang.String,java.lang.String)[pri:6, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="selectProductTest" duration-ms="9306" started-at="2022-05-04T18:13:36 IST" data-provider="getProductSelectData" finished-at="2022-05-04T18:13:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Macbook]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProductTest -->
        <test-method status="PASS" signature="selectProductTest(java.lang.String,java.lang.String)[pri:6, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="selectProductTest" duration-ms="10458" started-at="2022-05-04T18:13:46 IST" data-provider="getProductSelectData" finished-at="2022-05-04T18:13:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProductTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ba.democart.tests.AccountsPageTest@3eabe84a]" name="tearDown" is-config="true" duration-ms="0" started-at="2022-05-04T18:13:56 IST" finished-at="2022-05-04T18:13:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ba.democart.tests.AccountsPageTest -->
    </test> <!-- Accounts Page Test -->
  </suite> <!-- Open Cart Regression Suite -->
</testng-results>
